"use client";

import { useState } from "react";
import Link from "next/link";
import { cn } from "@/lib/utils";

const faqs = [
  {
    question: "Can business users access data without knowing SQL or Python?",
    answer: "Yes. Hex offers intuitive no-code cells and powerful AI assistance so anyone can confidently pull, filter, and visualize data without writing a single line of code.",
  },
  {
    question: "How does Hex ensure AI answers are accurate and trustworthy?",
    answer: "Hex relies on connected semantic layers, verified schemas, and transparent agentic reasoning steps so you can always audit how an answer was derived.",
  },
  {
    question: "How is Hex different from traditional BI tools like Tableau or Looker?",
    answer: "Unlike traditional BI, Hex supports both deep exploratory data science (Python/SQL notebooks) and interactive dashboards in the exact same platform.",
  },
  {
    question: "How is Hex different from just using ChatGPT or an AI assistant for data?",
    answer: "Hex's AI is deeply integrated with your secure data warehouse, understanding your specific environment, schemas, and metadata to generate safe, accurate queries.",
  },
  {
    question: "How is Hex different than other AI Analytics platforms?",
    answer: "Hex combines a best-in-class notebook environment with a beautiful app builder, meaning insights aren't just generated by AI—they are instantly shareable as interactive data apps.",
  },
  {
    question: "How is Hex different than point solution analytics tools?",
    answer: "Hex replaces multiple fragmented tools (SQL IDEs, Python notebooks, BI dashboards) with a unified workflow, drastically reducing context switching and overhead.",
  },
];

export function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="relative w-full border-b border-zinc-200/80 flex justify-center z-10 bg-transparent">
      <div className="flex w-full max-w-[1200px] flex-col items-center px-6 py-24 md:px-10 lg:px-12 relative">
        {/* Architect limits */}
        <div className="absolute left-0 right-0 top-0 h-px border-t border-dashed border-zinc-200/80 pointer-events-none hidden lg:block z-0" />

        <div className="w-full max-w-3xl relative z-10">
          <h2 className="text-center text-[2rem] md:text-[2.5rem] font-bold text-zinc-900 tracking-tight mb-12">
            FAQ
          </h2>
          
          <div className="flex flex-col border-t border-zinc-200">
            {faqs.map((faq, index) => (
              <div key={index} className="border-b border-zinc-200">
                <button
                  onClick={() => toggleFaq(index)}
                  className="w-full flex items-center justify-between py-5 text-left transition-colors hover:bg-zinc-50/50"
                  aria-expanded={openIndex === index}
                >
                  <span className="text-[14px] font-bold text-zinc-900 tracking-tight pr-8">
                    {faq.question}
                  </span>
                  <div className={cn("text-zinc-400 transition-transform duration-300", openIndex === index ? "rotate-90" : "")}>
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="9 18 15 12 9 6"></polyline>
                    </svg>
                  </div>
                </button>
                <div 
                  className={cn(
                    "overflow-hidden transition-all duration-300 ease-in-out",
                    openIndex === index ? "max-h-40 opacity-100 mb-5" : "max-h-0 opacity-0"
                  )}
                >
                  <p className="text-[14px] text-zinc-600 leading-relaxed pr-8">
                    {faq.answer}
                  </p>
                </div>
              </div>
            ))}
          </div>
          
          <div className="mt-12 text-center text-[13px] font-medium text-zinc-600">
             Can't find your answer here? <Link href="/contact" className="text-zinc-900 underline underline-offset-4 decoration-zinc-300 hover:decoration-zinc-900 transition-colors">Get in touch</Link>.
          </div>
        </div>
      </div>
    </section>
  );
}
